version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "10:00"
      timezone: "Europe/Amsterdam"
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "owanturist"
