export type * from "./result"
export * from "./validate-strategy"

// SIGNAL FORM

export type * from "./signal-form/get-signal-form-error"
export type * from "./signal-form/get-signal-form-error-setter"
export type * from "./signal-form/get-signal-form-error-verbose"
export type * from "./signal-form/get-signal-form-flag"
export type * from "./signal-form/get-signal-form-flag-setter"
export type * from "./signal-form/get-signal-form-flag-verbose"
export type * from "./signal-form/get-signal-form-input"
export type * from "./signal-form/get-signal-form-input-setter"
export type * from "./signal-form/get-signal-form-output"
export type * from "./signal-form/get-signal-form-output-verbose"
export type * from "./signal-form/get-signal-form-param"
export type * from "./signal-form/get-signal-form-validate-on"
export type * from "./signal-form/get-signal-form-validate-on-setter"
export type * from "./signal-form/get-signal-form-validate-on-verbose"
export * from "./signal-form/is-signal-form"
export type * from "./signal-form/signal-form"
export type * from "./signal-form/signal-form-params"

// FORM UNIT

export * from "./form-unit/form-unit"
export type * from "./form-unit/form-unit-error-setter"
export type * from "./form-unit/form-unit-flag-setter"
export type * from "./form-unit/form-unit-input-setter"
export type * from "./form-unit/form-unit-params"
export type * from "./form-unit/form-unit-transformer"
export type * from "./form-unit/form-unit-validate-on-setter"
export type * from "./form-unit/form-unit-validator"
export * from "./form-unit/is-form-unit"
export type * from "./form-unit/zod-like-schema"

// FORM SHAPE

export * from "./form-shape/form-shape"
export type * from "./form-shape/form-shape-error"
export type * from "./form-shape/form-shape-error-setter"
export type * from "./form-shape/form-shape-error-verbose"
export type * from "./form-shape/form-shape-fields"
export type * from "./form-shape/form-shape-flag"
export type * from "./form-shape/form-shape-flag-setter"
export type * from "./form-shape/form-shape-flag-verbose"
export type * from "./form-shape/form-shape-input"
export type * from "./form-shape/form-shape-input-setter"
export type * from "./form-shape/form-shape-output"
export type * from "./form-shape/form-shape-output-verbose"
export type * from "./form-shape/form-shape-params"
export type * from "./form-shape/form-shape-validate-on"
export type * from "./form-shape/form-shape-validate-on-setter"
export type * from "./form-shape/form-shape-validate-on-verbose"
export type * from "./form-shape/get-form-shape-param"
export * from "./form-shape/is-form-shape"

// FORM META

export type * from "./form-meta"

// FORM LIST

export * from "./form-list/form-list"
export type * from "./form-list/form-list-error"
export type * from "./form-list/form-list-error-setter"
export type * from "./form-list/form-list-error-verbose"
export type * from "./form-list/form-list-flag"
export type * from "./form-list/form-list-flag-setter"
export type * from "./form-list/form-list-flag-verbose"
export type * from "./form-list/form-list-input"
export type * from "./form-list/form-list-input-setter"
export type * from "./form-list/form-list-output"
export type * from "./form-list/form-list-output-verbose"
export type * from "./form-list/form-list-params"
export type * from "./form-list/form-list-validate-on"
export type * from "./form-list/form-list-validate-on-setter"
export type * from "./form-list/form-list-validate-on-verbose"
export * from "./form-list/is-form-list"

// FORM OPTIONAL

export * from "./form-optional/form-optional"
export type * from "./form-optional/form-optional-error"
export type * from "./form-optional/form-optional-error-setter"
export type * from "./form-optional/form-optional-error-verbose"
export type * from "./form-optional/form-optional-flag"
export type * from "./form-optional/form-optional-flag-setter"
export type * from "./form-optional/form-optional-flag-verbose"
export type * from "./form-optional/form-optional-input"
export type * from "./form-optional/form-optional-input-setter"
export type * from "./form-optional/form-optional-output"
export type * from "./form-optional/form-optional-output-verbose"
export type * from "./form-optional/form-optional-params"
export type * from "./form-optional/form-optional-schema"
export type * from "./form-optional/form-optional-validate-on"
export type * from "./form-optional/form-optional-validate-on-setter"
export type * from "./form-optional/form-optional-validate-on-verbose"
export * from "./form-optional/is-form-optional"

// FORM SWITCH

export * from "./form-switch/form-switch"
export type * from "./form-switch/form-switch-active-branch"
export type * from "./form-switch/form-switch-branch"
export type * from "./form-switch/form-switch-branches"
export type * from "./form-switch/form-switch-concise-schema"
export type * from "./form-switch/form-switch-error"
export type * from "./form-switch/form-switch-error-setter"
export type * from "./form-switch/form-switch-error-verbose"
export type * from "./form-switch/form-switch-flag"
export type * from "./form-switch/form-switch-flag-setter"
export type * from "./form-switch/form-switch-flag-verbose"
export type * from "./form-switch/form-switch-input"
export type * from "./form-switch/form-switch-input-setter"
export type * from "./form-switch/form-switch-output"
export type * from "./form-switch/form-switch-output-verbose"
export type * from "./form-switch/form-switch-params"
export type * from "./form-switch/form-switch-validate-on"
export type * from "./form-switch/form-switch-validate-on-setter"
export type * from "./form-switch/form-switch-validate-on-verbose"
export type * from "./form-switch/form-switch-verbose-schema"
export type * from "./form-switch/get-form-switch-branches-param"
export * from "./form-switch/is-form-switch"
