name: Restore environment

runs:
  using: composite
  steps:
    - name: Download dependencies
      uses: actions/download-artifact@v3
      with:
        name: dependencies

    - name: Unzip dependencies
      shell: bash
      run: unzip -q deps.zip

    - name: Install pnpm
      uses: ./.github/actions/install-pnpm
