name: Setup and cache dependencies

runs:
  using: composite
  steps:
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: "npm"

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
