name: Setup environment

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm i --prefer-offline
