name: Lint files

inputs:
  all_files:
    description: "Run eslint on all files, not just changed ones"
    required: true

runs:
  using: composite
  steps:
    - name: Lint all files
      if: ${{ inputs.all_files == 'true' }}
      shell: bash
      run: pnpm lint

    - name: Lint changed files
      if: ${{ inputs.all_files == 'false' }}
      uses: sibiraj-s/action-eslint@v2
      with:
        extensions: "js,jsx,ts,tsx"
        annotations: true
        root_dir: "./"
