name: Lint source code

inputs:
  all_files:
    description: "Run eslint on all files, not just changed ones"
    required: true

runs:
  using: composite
  steps:
    - name: Detect .eslintrc change
      id: changed-files
      uses: tj-actions/changed-files@v37
      with:
        files_yaml: |
          eslint:
            - .eslintrc.json
            - .eslintignore
            - pnpm-lock.yaml
          target:
            - "**/*.{ts,tsx,js,jsx}"

    - name: Lint all files
      id: lint-all
      if: ${{ inputs.all_files == 'true' || steps.changed-files.outputs.eslint_any_changed == 'true' }}
      shell: bash
      run: pnpm lint

    - name: Lint changed files
      if: ${{ steps.lint-all.outcome == 'skipped' && steps.changed-files.outputs.target_any_changed == 'true' }}
      shell: bash
      run: pnpm eslint ${{ steps.changed-files.outputs.target_all_changed_files }} --no-error-on-unmatched-pattern
