export type { Compare } from "./utils"
export { type ImpulseOptions, Impulse } from "./Impulse"
export { batch } from "./batch"
export { subscribe } from "./subscribe"
export { watch } from "./watch"
export { useImpulse } from "./useImpulse"
export { useImpulseValue } from "./useImpulseValue"
export { useTransmittingImpulse } from "./useTransmittingImpulse"
export { useImpulseMemo } from "./useImpulseMemo"
export { useImpulseCallback } from "./useImpulseCallback"
export { useImpulseEffect } from "./useImpulseEffect"
export { useImpulseLayoutEffect } from "./useImpulseLayoutEffect"
export { type UseWatchImpulseOptions, useWatchImpulse } from "./useWatchImpulse"
