#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"

set -x

# Based on a hook from gist.github.com
# Source: https://gist.github.com/zgohr/4557894

checkout_type=$3

if [ "$checkout_type" -ne 1 ]
then
  exit 0 ; # Not a branch checkout
fi

branch_name=$(git rev-parse --abbrev-ref HEAD)

if ! [[ "$branch_name" =~ ^(v([0-9]+\.){1,2}x|master|next|alpha|beta|snapshot)$ ]];
then
  exit 0 ; # Does not match release branch pattern
fi

# change .changeset/config.json baseBranch to the current branch
perl -i -pe"s/\"baseBranch\":.*/\"baseBranch\": \"$branch_name\",/g" .changeset/config.json

# exit if there are no changes in .changeset/config.json
if [ -z "$(git status --porcelain .changeset/config.json)" ]; then
  exit 0
fi

# Create a commit and display a message
git add .changeset/config.json
git commit -m "Set .changeset.baseBranch to '$branch_name'" --no-verify
