#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Based on a hook from gist.github.com
# Source: https://gist.github.com/zgohr/4557894

from_hash=$1
to_hash=$2
checkout_type=$3
branch_name=$(git rev-parse --abbrev-ref HEAD)
from_branch_name=$(git name-rev --name-only $from_hash)


if [ $checkout_type -ne 1 ]
then
    exit 0 ; # Not a branch checkout
fi

if [ $from_hash != $to_hash ]
then
    exit 0 ; # Not checking out a new branch
fi

if [ $branch_name == $from_branch_name ]
then
    exit 0 ; # Not checking out a new branch
fi

# exit if does not match release branch pattern
if ! [[ $branch_name =~ ^(v([0-9]\.){1,2}x|master|next|alpha|beta|snapshot)$ ]]; then
  exit 0
fi

# change .changeset/config.json baseBranch to the current branch
perl -i -pe"s/\"baseBranch\":.*/\"baseBranch\": \"$branch_name\",/g" .changeset/config.json

# Create a commit and display a message
git add .changeset/config.json
git commit -m "Set .changeset.baseBranch to '$branch_name'" --no-verify
