name: main

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  install:
    name: Install node_modules
    runs-on: ubuntu-latest

    steps:
      - name: Setup dependencies
        uses: ./.github/actions/setup.yml

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --no-audit

  lint:
    name: Lint
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Setup dependencies
        uses: ./.github/actions/setup.yml

      - name: Lint
        run: npm run lint

  typecheck:
    name: Type check
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Setup dependencies
        uses: ./.github/actions/setup.yml

      - name: Type check
        run: npm run typecheck

  test:
    name: Test with React 18
    needs: install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Setup dependencies
        uses: ./.github/actions/setup.yml

      - name: Test
        run: npm test -- --run

  react:
    name: Test with React ${{ matrix.react-version }}
    needs: install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        react-version: [17, 16]

    steps:
      - name: Setup dependencies
        uses: ./.github/actions/setup.yml

      - name: Install React ${{ matrix.react-version }}
        run: >
          npm i --no-save --force
          react@${{ matrix.react-version }}
          @testing-library/react@12
          @testing-library/react-hooks@7

      - name: Test
        run: npm test -- --run
