name: main

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  install:
    name: Install node_modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dependencies
        uses: ./.github/actions/setup

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --no-audit --no-fund

  lint:
    name: Lint
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dependencies
        uses: ./.github/actions/setup

      - name: Lint
        run: npm run lint

  typecheck:
    name: Type check
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dependencies
        uses: ./.github/actions/setup

      - name: Type check
        run: npm run typecheck

  test:
    name: Test with React 18
    needs: install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dependencies
        uses: ./.github/actions/setup

      - name: Test
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true

  react:
    name: Test with React ${{ matrix.react-version }}
    needs: install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        react-version: [17, 16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dependencies
        uses: ./.github/actions/setup

      - name: Install React ${{ matrix.react-version }}
        run: >
          npm i --no-save --force --no-fund
          react@${{ matrix.react-version }}
          @testing-library/react@12
          @testing-library/react-hooks@7

      - name: Test
        run: npm test -- --run
