name: main

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  install:
    name: Install node_modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile --prefer-offline

      - name: Zip dependencies for uploading
        # [q] quite
        # [r] recursive
        # [y] store symlinks as symlinks
        run: zip -qry deps.zip ./node_modules

      - name: Upload dependencies artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dependencies
          path: deps.zip
          retention-days: 7
          if-no-files-found: error

  lint:
    name: Lint
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download dependencies
        uses: ./.github/actions/download-deps

      - name: Lint
        run: pnpm lint

  typecheck:
    name: Type check
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download dependencies
        uses: ./.github/actions/download-deps

      - name: Type check
        run: pnpm typecheck

  test:
    name: Test with React 18
    needs: install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download dependencies
        uses: ./.github/actions/download-deps

      - name: Test
        run: pnpm test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false

  react:
    name: Test with React ${{ matrix.react-version }}
    needs: install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        react-version: [17, 16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download dependencies
        uses: ./.github/actions/download-deps

      - name: Install React ${{ matrix.react-version }}
        run: |
          pnpm add -D react@${{ matrix.react-version }} @testing-library/react-hooks@7
          pnpm add -D @testing-library/react@12

      - name: Test
        run: pnpm test -- --run
