name: main

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  install:
    name: Install node_modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Install dependencies
        run: npm ci --no-audit --no-fund --prefer-offline

      - name: Zip dependencies for uploading
        run: zip deps.zip ./node_modules -r

      - name: Upload dependencies artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dependencies
          path: deps.zip
          retention-days: 7
          if-no-files-found: error

  lint:
    name: Lint
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download dependencies
        uses: ./.github/actions/download-deps

      - name: Lint
        run: npm run lint

  typecheck:
    name: Type check
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download dependencies
        uses: ./.github/actions/download-deps

      - name: Type check
        run: npm run typecheck

  test:
    name: Test with React 18
    needs: install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download dependencies
        uses: ./.github/actions/download-deps

      - name: Test
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true

  react:
    name: Test with React ${{ matrix.react-version }}
    needs: install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        react-version: [17, 16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download dependencies
        uses: ./.github/actions/download-deps

      - name: Install React ${{ matrix.react-version }}
        run: |
          npm i -D --force --no-fund --no-audit react@${{ matrix.react-version }} @testing-library/react-hooks@7
          npm i -D --force --no-fund --no-audit @testing-library/react@12

      - name: Test
        run: npm test -- --run
