name: release

on:
  workflow_run:
    types:
      - completed
    workflows:
      - ci
    branches:
      - master

env:
  CI: true

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release on npm
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Get changeset status
        run: pnpm cs status --output ./changeset-status.json

      - name: Read the new version
        id: status
        uses: notiz-dev/github-action-json-property@release
        with:
          path: ./changeset-status.json
          prop_path: "releases.0.newVersion"

      - name: Build source code
        run: pnpm build

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm publish
          commit: Release ${{ steps.status.outputs.propStr }}
          title: Release ${{ steps.status.outputs.propStr }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
