name: Release

on:
  push:
    branches:
      - master
      - v[0-9]+.x
      - v[0-9]+.[0-9]+.x

env:
  CI: true

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release on npm
    runs-on: ubuntu-latest
    # prevents this action from running on forks
    if: ${{ github.repository_owner == 'owanturist' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: ./.github/actions/setup-env
      - uses: ./.github/actions/run-checks

      - name: Get changeset status
        run: pnpm cs status --output ./changeset-status.json

      - name: Read the new version
        id: new-version
        uses: notiz-dev/github-action-json-property@release
        continue-on-error: true
        with:
          path: ./changeset-status.json
          prop_path: "releases.0.newVersion"

      - name: Read the old version
        id: old-version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: ./package.json
          prop_path: "version"

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm run publish --tag=${{ github.ref_name == 'master' && 'latest' || '' }}
          commit: Release `${{ steps.old-version.outputs.prop }}` -> `${{ steps.new-version.outputs.prop }}`
          title: Release `${{ steps.old-version.outputs.prop }}` -> `${{ steps.new-version.outputs.prop }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
