name: release

on:
  workflow_run:
    types:
      - completed
    workflows:
      - ci
    branches:
      - master

env:
  CI: true

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release on npm
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Run changesets
        run: pnpm cs version

      - name: Read package.json info
        id: info
        uses: jaywcjlove/github-action-package@main

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm build && pnpm publish --no-git-checks
          commit: Release ${{ steps.info.outputs.version }}
          title: Release ${{ steps.info.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  fail:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The ci workflow failed'
      - run: exit 1
